sudo: required
services:
  - docker

before_install:
  - docker build -t ckuninty/react-test -f ./client/Dockerfile.dev .

script:
  - docker run ckuninty/react-test npm test -- --coverage

after_success:
  - docker build -t ckuninty/multi-client ./client
  - docker build -t ckuninty/multi-nginx ./nginx
  - docker build -t ckuninty/multi-server ./server
  - docker build -t ckuninty/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push ckuninty/multi-client
  - docker push ckuninty/multi-nginx
  - docker push ckuninty/multi-server
  - docker push ckuninty/multi-worker

